apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j7ptic9ny-python
  janus-idp.io/tekton: j7ptic9ny-python
  backstage.io/kubernetes-id: j7ptic9ny-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j7ptic9ny-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
