apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: j7ptic9ny-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: j7ptic9ny-python 
  name: j7ptic9ny-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: j7ptic9ny-python
    weight: 100 
